fix: dbus 适配screencast、remotedesktop
linuxdeepin/xdg-desktop-portal-dde pull request #26
Opened 2023-05-08 10:10 UTC by myk1343

dbus 适配screencast、remotedesktop

Log: dbus 适配screencast、remotedesktop

2023-05-09 01:51 UTC, justforlxz requested changes

2023-05-09 01:51 UTC, justforlxz commented on src/CMakeLists.txt
> +  /usr/include/glib-2.0
用 find_package 或者 pkg_search_modules 去查找，不要硬编码 include 路径。

2023-05-09 01:51 UTC, justforlxz commented on src/remotedesktop.cpp
> +Q_LOGGING_CATEGORY(XdgDesktopPortalKdeRemoteDesktop, "xdp-kde-remotedesktop")
改成 deepin 的，不要带有 kde 的信息。

2023-05-10 07:45 UTC, myk1343 commented on src/remotedesktop.cpp
> +Q_LOGGING_CATEGORY(XdgDesktopPortalKdeRemoteDesktop, "xdp-kde-remotedesktop")
已修改

2023-05-10 07:45 UTC, myk1343 commented on src/CMakeLists.txt
> +  /usr/include/glib-2.0
已修改

2023-05-10 09:09 UTC, ssk-wh commented on src/CMakeLists.txt
> +    ${SRC}
和上面的文件放到一起，不需要单独再起一个

2023-05-10 09:09 UTC, ssk-wh commented on src/ddesktopportal.cpp
> +		WaylandIntegration::init();
不要用tab，格式整理下

2023-05-10 09:09 UTC, ssk-wh commented on src/ddesktopportal.h
> +    RemoteDesktopPortal *m_remote;
初始化赋值， = nullptr，保持一致

2023-05-10 09:44 UTC, myk1343 commented on src/CMakeLists.txt
> +
已修改

2023-05-10 09:47 UTC, ssk-wh submitted a review, later dismissed

2023-05-10 10:05 UTC, justforlxz requested changes

2023-05-11 02:11 UTC, justforlxz approved these changes

2023-05-11 02:12 UTC, myk1343 commented
/merge

2023-05-11 02:14 UTC, merged