chore(tag): 1.0.4
linuxdeepin/xdg-desktop-portal-dde pull request #35
Opened 2023-06-09 08:41 UTC by Decodetalkers

Log: new tag

2023-06-09 08:44 UTC, Decodetalkers commented
我似乎搞错流程了，补个tag

2023-06-12 05:47 UTC, Zeno-sole commented
/integrate

2023-06-12 05:48 UTC, BLumia requested changes

2023-06-12 05:48 UTC, BLumia commented on debian/changelog
> + -- fanpengcheng <chenhongtao@deepin.org>  Fri, 9 Jun 2023 16:21:26 +0800
？

2023-06-12 05:54 UTC, BLumia approved these changes

2023-06-12 06:24 UTC, Zeno-sole commented
/integrate

2023-06-12 08:52 UTC, Zeno-sole commented
/merge

2023-06-12 09:18 UTC, Decodetalkers commented
/merge

2023-06-12 09:19 UTC, merged