fix: modify accessdialog to dtk style
linuxdeepin/xdg-desktop-portal-dde pull request #56
Opened 2024-10-09 07:20 UTC by fly602

modify accessdialog to dtk style

2024-10-09 07:33 UTC, BLumia commented on src/CMakeLists.txt
> +    ${DtkWidget_LIBRARIES}
考虑改成 `Dtk6::Widget` ？

2024-10-09 07:36 UTC, BLumia requested changes

2024-10-09 07:36 UTC, BLumia commented on src/accessdialog.cpp
> +accessDialog::accessDialog(const QString &app_id, const QString &parent_window, const QString &title, const QString &subtitle, const QString &body, const QVariantMap &options) :
为啥这个 accessDialog 是首字母小写的？

2024-10-09 08:57 UTC, fly602 commented on src/CMakeLists.txt
> +    ${DtkWidget_LIBRARIES}
已修改

2024-10-09 08:58 UTC, fly602 commented on src/accessdialog.cpp
> +accessDialog::accessDialog(const QString &app_id, const QString &parent_window, const QString &title, const QString &subtitle, const QString &body, const QVariantMap &options) :
由于前面有个方法重名了，所以这里偷了个懒，现在改用using起了个别名

2024-10-28 06:31 UTC, BLumia approved these changes

2024-10-28 06:33 UTC, merged